server:
  port: 8200
  servlet:
    session:
      # 单位为秒
      timeout: 1800
management:
  health:
    redis:
      enabled: false
spring:
  profiles:
    active: dev
  application:
    name: oup-console
  resources:
    static-locations: classpath:/static/
  zipkin:
    baseUrl: http://localhost:9411
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**
  thymeleaf:
  #生产环境建议打开，便于文件加载加速，也可考虑nginx、cdn对资源加速。
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: console:session
  cache:
    cache-names: commCache,sessionCache
  redis:
    timeout: 60
    cluster:
      max-redirects: 3
      nodes:
        - localhost:7000
        - localhost:7001
        - localhost:7002
        - localhost:7003
        - localhost:7004
        - localhost:7005
      testOnReturn: true
      maxIdle: 10
      minIdle: 2
      maxWaitMills: 3000
      testOnBorrow: true
      maxTotal: 4
  pool:
    max-active: 10
    max-idle: 10
    max-wait: -1
    min-idle: 1
    timeout: 2000
#*****************************logging config**************************
logging:
  file: D:/logs/web.log
  level:
    root: info
    com.yasaka.stock: info
    com.oup.service: debug
#*****************************app config**************************
#支持自定义扩展属性
console:
  app_name: 统一开发平台
  #公共管理模式 0-标准模式 1-复杂模式，环境变量使用man_mode
  man_mode: 0
  super_user_id: admin
  super_user_pwd: admin123
  err_url_403: /error/403.html
  CUS_PARA:
    -para1:22
  login_success_url: /index
  login_fail_url: /
  #文件传输根地址
  file_base_url: D:\workspace\ext
#cdn专用、文件传输服务器
#  thymeleaf:
#    static_loc: http://localhost:8200
#    file_loc: http://localhost:8200

