server:
  port: 8200
spring:
  profiles:
    active: dev
  application:
    name: oup-console
  zipkin:
    baseUrl: http://localhost:9411
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**
  thymeleaf:
  #生产环境建议打开，便于文件加载加速，也可考虑nginx、cdn对资源加速。
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  session:
    store-type: redis
  cache:
    cache-names: commCache,sessionCache
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
      testOnReturn: true
      maxIdle: 10
      minIdle: 2
      maxWaitMills: 3000
      testOnBorrow: true
      maxTotal: 4
  pool:
    max-active: 10
    max-idle: 10
    max-wait: -1
    min-idle: 1
  timeout: 2000
#*****************************logging config**************************
logging:
  file: D:/logs/web.log
  level:
    root: info
    com.yasaka.stock : info
    com.oup.service: debug